### ISSUE TITLE
Function match should catch exception?

### ISSUE THREAD

**Issue by dawncold** [moq/moq4#1010]
Moq version: 4.14.0

When I run test like this, I got an exception, it looks like `Single` method raise exception when a list with two or more elements passed to it.

Workaround code:
change `m.Actions.Single() == Action.View` to `m.Actions.Count == 1 && m.Actions[0] == Action.View`

I'm not sure whether it is possible when match function throws an exception, as a mismatch?

This is my test codes
```csharp
public class Test
{
    [Fact]
    public void test()
    {
        var mockedPermissionService = new Mock<IPermissionService>();
        mockedPermissionService.Setup(lib =>
            lib.Permission(It.Is<PermissionRequest>(m =>
                m.SubjectId == 1 && m.Actions.Single() == Action.View)))
            .Returns(1);
        mockedPermissionService.Setup(lib => 
                lib.Permission(It.Is<PermissionRequest>(m =>
                    m.SubjectId == 1 && m.Actions.Count == 2)))
            .Returns(2);
        mockedPermissionService.Setup(lib => 
                lib.Permission(It.Is<PermissionRequest>(m =>
                    m.SubjectId == 1 && m.Actions.Single() == Action.Delete)))
            .Returns(3);

        var permissionService = mockedPermissionService.Object;
        var result1 = permissionService.Permission(new PermissionRequest
        {
            Actions = new List<Action>{ Action.View },
            SubjectId = 1,
            ObjectId = 1
        });
        var result2 = permissionService.Permission(new PermissionRequest
        {
            Actions = new List<Action> { Action.View, Action.Delete },
            SubjectId = 1,
            ObjectId = 2
        });
        Assert.Equal(1, result1);
        Assert.Equal(2, result2);
    }
}
```

Exception:
```
TestMoq.Test.test

System.InvalidOperationException: Sequence contains more than one element

System.InvalidOperationException
Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at lambda_method(Closure , PermissionRequest )
   at Moq.InvocationShape.IsMatch(Invocation invocation)
   at Moq.SetupCollection.FindMatchFor(Invocation invocation)
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock)
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IPermissionServiceProxy.Permission(PermissionRequest request)
   at TestMoq.Test.test() in C:\Users\Administrator\RiderProjects\TestMoq\TestMoq\Program.cs:line 34
```

**Comment by stakx** [comment]
Seems like you really want to use `.FirstOrDefault()`, not `.Single()`.

**Comment by dawncold** [comment]
Yes, there are some workaround expressions.

So we should be careful on match expression as it could raise exception?

**Comment by stakx** [comment]
> So we should be careful on match expression as it could raise exception?

The LINQ `.Single()` operator is *supposed to* raise an exception when applied to a sequence with either zero or more than one items, this has nothing to do with Moq. Why should they catch exceptions for you? That's not what they're for.

**Comment by dawncold** [comment]
Well, I think `m.Actions.Single() == Action.View` has a better readability.

**Comment by stakx** [comment]
If you choose to use a method that may throw over a largely equivalent method that won't throw, fine... it's your code. But it is on you to deal with the consequence of that choice (exceptions being thrown).

It is not the Moq library's responsibility to randomly swallow user exceptions.
