### ISSUE TITLE
NullReferenceException thrown by Microsoft.CSharp when using Generic Interfaces and Dynamic

### ISSUE THREAD

**Issue by AmitGee** [moq/moq4#114]
I posted this to code.google.com (#376) before realising that the site had moved. The following code produces a NullRef exception

I'm using Win7, Moq 4.2.1402.2112, .NET 4.5.1

The exception occurs when using a mock of the generic interface, when the type argument is of type object. It **doesn't** occur when:
1. using a custom reference type or a value type as the type argument, 
2. using a mock of the non-generic interface, 
3. not using moq

The full stack trace of the error is below the code. 

``` csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Moq;

namespace TestDynamic
{
    public interface IInterface<T>
    {
        T DoStuff(T input);
    }

    public interface IInterface
    {
        object DoStuff(object input);
    }

    class Program
    {
        static void Main(string[] args)
        {
            var m = new MockRepository(MockBehavior.Default);
            var mi = m.Create<IInterface>();
            var miGeneric = m.Create<IInterface<object>>();
            var miGenericString = m.Create<IInterface<string>>();

            var input = new object();
            var expectedOutput = new object();

            mi.Setup(i => i.DoStuff(input)).Returns(expectedOutput);
            miGeneric.Setup(i => i.DoStuff(input)).Returns(expectedOutput);
            miGenericString.Setup(i => i.DoStuff("input")).Returns("output");

            var p = new Program();

            //var output = p.NonGenericDoStuff(mi.Object, input); // ok
            var output = p.GenericDoStuff(miGeneric.Object, input);// throws
            //var output = p.GenericDoStuff(miGenericString.Object, "input"); // ok

            Console.WriteLine(output);
        }

        private T GenericDoStuff<T>(IInterface<T> obj, T input)
        {
            dynamic o = obj;
            var output = o.DoStuff(input);
            return output; // throws NullRef
        }


        private object NonGenericDoStuff(IInterface obj, object input)
        {
            dynamic o = obj;
            var output = o.DoStuff(input);
            return output;
        }
    }
}
```

Stack trace:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.GenerateLambda(EXPRCALL pExpr)
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.VisitCALL(EXPRCALL pExpr)
   at Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Dispatch(EXPR pExpr)
   at Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Visit(EXPR pExpr)
   at Microsoft.CSharp.RuntimeBinder.ExpressionTreeCallRewriter.Rewrite(TypeManager typeManager, EXPR pExpr, IEnumerable`1 listOfParameters)

   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateExpressionTreeFromResult(IEnumerable`1 parameters, ArgumentObject[] arguments, Scop
e pScope, EXPR pResult)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(DynamicMetaObjectBinder payload, IEnumerable`1 parameters, DynamicMetaObject[] a
rgs, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, IEnumerable`1 parameters, DynamicMetaObject[] args,
 DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, IEnumerable`1 args, IEnumerable
`1 arginfos, DynamicMetaObject onBindingError)
   at Microsoft.CSharp.RuntimeBinder.CSharpConvertBinder.FallbackConvert(DynamicMetaObject target, DynamicMetaObject errorSuggestion)
   at System.Dynamic.DynamicMetaObject.BindConvert(ConvertBinder binder)
   at System.Dynamic.ConvertBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at TestDynamic.Program.GenericDoStuffDynamic[T](IInterface`1 obj, T input) in c:\TFS\TestProjects\TestDynamic\TestDynamic\Program.cs:line
 37
   at TestDynamic.Program.Main(String[] args) in c:\TFS\TestProjects\TestDynamic\TestDynamic\Program.cs:line 27
```

**Comment by stakx** [comment]
@AmitGee: Moq actually handles this just fine. You might have noticed that the exception does not get thrown by the mock invocation, but by the `return` statement in your method:

> ```csharp
> private T GenericDoStuff<T>(IInterface<T> obj, T input)
> {
>     dynamic o = obj;
>     var output = o.DoStuff(input);
>     return output; // throws NullRef
> }
> ```

That is, you do have a return value stored in `output`, but the Dynamic Language Runtime cannot convert it directly to type `T`. See what happens when you replace `return output;` with `return (T)(object)output;`, i.e. when you first "cast" from `dynamic` to `object`, and then have a regular type cast from `object` to `T`.
