### ISSUE TITLE
SetupAllProperties with DefaultValue.Mock throws on concrete property type without parameterless constructor

### ISSUE THREAD

**Issue by ploeh** [moq/moq4#149]
# Steps to reproduce:
1. Create a `Mock` of an interface with a writeable property, where the property type is a concrete type without a parameterless constructor.
2. Set `DefaultValue` to `DefaultValue.Mock`
3. Call `SetupAllProperties`

Here's an example:

``` C#
public interface IHasAProperty
{
    Uri Url { get; set; }
}

[Fact]
public void Repro()
{
    var m = new Mock<IHasAProperty>();
    m.DefaultValue = DefaultValue.Mock;
    m.SetupAllProperties(); // Throws
}
```
# Expected outcome

The mock's behaviour should now have 'property behaviour', and no exception should have been thrown.
# Actual outcome

The call to `SetupAllProperties` throws an exception. Here's the exception thrown by the above example:

```
Test 'ClassLibrary1.Tests.Repro' failed: System.ArgumentException : A matching constructor for the given arguments was not found on the mocked type.
---- System.MissingMethodException : Constructor on type 'UriProxy8985c2aafdc84af0b77d8b098416d187' not found.
    at Moq.Mock`1.<InitializeInstance>b__0()
    at Moq.PexProtector.Invoke(Action action)
    at Moq.Mock`1.InitializeInstance()
    at Moq.Mock`1.get_Object()
    at Moq.Mock`1.GetObject()
    at Moq.MockDefaultValueProvider.ProvideDefault(MethodInfo member, Object[] arguments)
    at Moq.Mock.<>c__DisplayClass27.<SetupAllProperties>b__23()
    at Moq.PexProtector.Invoke(Action action)
    at Moq.Mock.SetupAllProperties(Mock mock)
    at Moq.Mock`1.SetupAllProperties()
    Tests.cs(18,0): at ClassLibrary1.Tests.Repro()
    ----- Inner Stack Trace -----
    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
    at System.Activator.CreateInstance(Type type, Object[] args)
    at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
    at Moq.Mock`1.<InitializeInstance>b__0()
```

If you comment out the line that sets `DefaultValue` to `DefaultValue.Mock`, not exception is thrown.

**Comment by stakx** [comment]
Hi @ploeh, just for the record, the issue you reported is no longer reproducible starting with Moq version 4.5.19.
