### ISSUE TITLE
Thread safety issue on setup  

### ISSUE THREAD

**Issue by jonhwong** [moq/moq4#326]
The following test code produces an IndexOutOfRangeException error on v4.7.0

```csharp
class Program
{
    public static void Main()
    {
        for (int i = 0; i < 1000; i++)
        {
            Mock<IInterface> m = new Mock<IInterface>(MockBehavior.Strict);

            Parallel.For(0, 100,
                j =>
                {
                    m.Setup(x => x.Get(j)).Returns(j);
                    Console.WriteLine($"{j}:{m.Object.Get(j)}");
                });
        }
    }
}
```

```
Exception:
System.IndexOutOfRangeException was unhandled by user code
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=mscorlib
  StackTrace:
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at Moq.Interceptor.AddCall(IProxyCall call, SetupKind kind)
       at Moq.Mock.<>c__DisplayClass65_0`2.<Setup>b__0()
       at Moq.PexProtector.Invoke[T](Func`1 function)
       at Moq.Mock.Setup[T,TResult](Mock`1 mock, Expression`1 expression, Condition condition)
       at Moq.Mock`1.Setup[TResult](Expression`1 expression)
       at ScratchPad.Program.<>c__DisplayClass0_0.<Main>b__0(Int32 j) in C:\test\ScratchPad\Program.cs:line 24
       at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
  InnerException: 
  …
```
The issue was initially seen when using Moq to implement a single instance WCF service host for integration testing.

**Comment by stakx** [comment]
Given the amount of iterations, could this be related to #227?

I ran your test code the other day and got the exception around `i == 890`. When I moved `m.Setup(x => x.Get(j)).Returns(j);` out of the `Parallel.For` into a separate regular `for` loop (before the parallel loop), the code ran to completion without error.

That might help you, but some more digging is required.

**Comment by stakx** [comment]
This will be fixed in the next release of Moq.
