### ISSUE TITLE
Symbols for Moq 4.7.8

### ISSUE THREAD

**Issue by kichalla** [moq/moq4#338]
**Question**: Where can I find the symbols for Moq 4.7.8?

We are hitting an issue while running tests in net46 with the following error and I am trying to see for which type this error is being thrown: 
```
      System.ArgumentException : Interface not found.
      Stack Trace:
           at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(RuntimeTypeHandle handle, RuntimeTypeHandle interfaceHandle)
           at System.RuntimeType.GetInterfaceMap(Type ifaceType)
           at Moq.Extensions.IsGetObjectDataVirtual(Type typeToMock)
           at Moq.Extensions.IsSerializableMockable(Type typeToMock)
           at Moq.SerializableTypesValueProvider.ProvideDefault(MethodInfo member)
           at Moq.Mock.GetInitialValue(IDefaultValueProvider valueProvider, Stack`1 mockedTypesStack, PropertyInfo property)
           at Moq.Mock.SetupAllProperties(Mock mock, Stack`1 mockedTypesStack)
           at Moq.Mock.<>c__DisplayClass72_0.<SetupAllProperties>b__0()
           at Moq.PexProtector.Invoke(Action action)
           at Moq.Mock.SetupAllProperties(Mock mock)
           at Moq.Mock`1.SetupAllProperties()
           at Moq.Mocks.<CreateMocks>d__6`1.MoveNext()
           at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
           at Moq.Linq.MockQueryable`1.Execute[TResult](Expression expression)
           at Moq.Mock.Of[T]()
```
Just FYI:
Repro: `var httpContext = Mock.Of<HttpContext>();`

Type: `https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/HttpContext.cs#L16`

**Comment by kichalla** [comment]
Ignore this. I was able to build the source successfully from Visual Studio. (before filing this issue I did try building from source, but it was from command line and which failed)
