### ISSUE TITLE
Given `mock.SetupGet(o => o.Property).CallBase()`, strict mocks throw, demanding that the setup provide a return value

### ISSUE THREAD

**Issue by stakx** [moq/moq4#448]
Strict mocks verify that setups for property getters actually specify some return value. (For the same reason that C# enforces non-`void` methods to return a value if they don't throw an exception first, so that verification is perfectly reasonable.)

The following test fails:

```csharp
public class Foo
{
    public virtual bool BooleanProperty => true;
}

[Fact]
var mock = new Mock<Foo>(MockBehavior.Strict);
mock.SetupGet(_ => _.BooleanProperty).CallBase();
Assert.True(mock.Object.BooleanProperty);
```

> Moq.MockException: **Foo.BooleanProperty invocation failed with mock behavior Strict.**
> **Invocation needs to return a value and therefore must have a corresponding setup that provides it.**
>    at Moq.ExecuteCall.ThrowIfReturnValueRequired(IProxyCall call, ICallContext invocation)
>    at Moq.ExecuteCall.HandleIntercept(ICallContext invocation, InterceptorContext ctx, CurrentInterceptContext localctx)
>    at Moq.Interceptor.Intercept(ICallContext invocation)
>    at Moq.Proxy.CastleProxyFactory.Interceptor.Intercept(IInvocation invocation)
>    at Castle.DynamicProxy.AbstractInvocation.Proceed()
>    at Castle.Proxies.FooProxy.get_BooleanProperty()
>    at …

However, it should pass because `BooleanProperty` **has** been set up to return a value; not an explicitly specified value (`.Returns(…)`), but whatever the base class' (`Foo`'s) `BooleanProperty` returns (`.CallBase()`).

**Comment by stakx** [comment]
This will be fixed in the next release of Moq (version > 4.7.99).
