### ISSUE TITLE
Occational null ref in CreateProxy

### ISSUE THREAD

**Issue by HaoK** [moq/moq4#653]
We are seeing some rare null refs come from Moq: original issue: https://github.com/aspnet/Identity/issues/1912
```
 var store = new Mock<IUserStore<TUser>>();
 var mgr = new Mock<UserManager<TUser>>(store.Object, null, null, null, null, null, null, null, null);
```

There's not too much going on here, but this sometimes fails rarely with:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
   at Moq.Mock`1.<InitializeInstance>b__20_0()
   at Moq.Mock`1.OnGetObject()
   at Moq.Mock`1.get_Object()
   at Microsoft.AspNetCore.Identity.Test.MockHelpers.MockUserManager[TUser]() in /_/test/Shared/MockHelpers.cs:line 22
   at Microsoft.AspNetCore.Identity.Test.SignInManagerTest.SetupUserManager(PocoUser user)
   at Microsoft.AspNetCore.Identity.Test.SignInManagerTest.CanExternalSignIn(Boolean isPersistent, Boolean supportsLockout) in /_/test/Identity.Test/SignInManagerTest.cs:line 523
```

Any ideas what could be going on?

**Comment by stakx** [comment]
@HaoK, I cannot explain the failure without further digging, but I know these code paths quite well. At first glance, it appears that DynamicProxy is failing unexpectedly while trying to look up the requested proxy type in its type cache.

We have recently fixed some concurrency / threading issues in Castle DynamicProxy related to `ObtainProxyType` (which is near the top of your stack trace)&mdash;see the [DynamicProxy changelog entry](https://github.com/castleproject/Core/blob/master/CHANGELOG.md#431-2018-06-21).

For this reason, I would suggest that you e.g. update Moq to version 4.9.0, which uses DynamicProxy 4.3.1. There's a slim chance that this might resolve your issue. (Note also that we've had reports that upgrading Moq from 4.7 to 4.8 / 4.9 might cause some inital assembly binding problems because recent Moq versions reference some additional `System.*` NuGet packages related to `ValueTask` and `ValueTuple`. These binding redirect issues can usually be resolved quite easily. Just giving you a heads up in case you run into this.)

If an upgrade to Moq doesn't resolve this issue, we'll need to take a closer look.

Please let me know if you're OK with proceeding in this manner.
