### ISSUE TITLE
System.ArgumentException: Interface not found in v.4.13.0 but not before.

### ISSUE THREAD

**Issue by vslynko** [moq/moq4#942]
Full sample available [Gist](https://gist.github.com/vslynko/c4fdd0187b5a29e7326889aa2bbb1baf)
__Debug build for net472__
Exception thrown for me
```stacktrace
System.ArgumentException: Interface not found.
   at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(RuntimeTypeHandle handle, RuntimeTypeHandle interfaceHandle)
   at System.RuntimeType.GetInterfaceMap(Type ifaceType)
   at Moq.Extensions.GetImplementingMethod(MethodInfo method, Type proxyType)
   at Moq.InvocationShape.IsOverride(Invocation invocation)
   at Moq.InvocationShape.IsMatch(Invocation invocation)
   at Moq.Setup.Matches(Invocation invocation)
   at Moq.SetupCollection.FindMatchFor(Invocation invocation)
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock)
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation)
   at Moq.Internals.InterfaceProxy.ToString()
   at MoqRegressionSample.MoqIssue.Fails() in C:\src\wavecontrol\src\WAVE.Device.Com.Tests\DeviceLink\MoqIssue.cs:line 33
```

![image](https://user-images.githubusercontent.com/12891283/66994587-c6748e00-f0cd-11e9-91b0-48c2075b543d.png)

**Comment by stakx** [comment]
Thanks for reporting, @vslynko. That's indeed a regression in 4.13.0. Fortunately one that is very easily fixed. Look out for the version 4.13.1 release, which should be ready during the next 10 days or so.
